Repository COSC-499-Group-C/FoodSaviour-frontend, pull requests merged in 2023-03, with the labels that each got.

#71 added navbar support for sharing and tracker
  food-saviour/src/addons/Navbar.js
  food-saviour/src/pages/HomeLogin.js
  food-saviour/src/pages/Sharing.js
  food-saviour/src/pages/Tracker.js
Labels: Chore

#76 Updated Login and Register functionality
  food-saviour/.env
  food-saviour/src/App.js
  food-saviour/src/actions/auth.js
  food-saviour/src/addons/Navbar.js
  food-saviour/src/axios.js
  food-saviour/src/components/CSRFToken.js
  food-saviour/src/components/Logout.js
  food-saviour/src/pages/Login.js
Labels: Task

#80 Tracker axios initial commit and refactoring
  food-saviour/src/components/Navbar.js
  food-saviour/src/components/PieChart.js
  food-saviour/src/pages/HomeLogin.js
  food-saviour/src/pages/Sharing.js
  food-saviour/src/pages/Tracker.js
Labels: Chore, Task

#82 meeting minutes for past 3 weeks
  documents/client/meeting-minutes/2023-02-01.md
  documents/client/meeting-minutes/2023-02-08.md
  documents/client/meeting-minutes/2023-02-15.md
Labels: Chore

#85 Make quotations uniform and format code
  food-saviour/src/App.js
  food-saviour/src/axios.js
  food-saviour/src/components/Logout.js
  food-saviour/src/components/Navbar.js
  food-saviour/src/css/App.css
  food-saviour/src/css/index.css
  food-saviour/src/css/sharing.css
  food-saviour/src/index.js
  food-saviour/src/pages/Home.js
  food-saviour/src/pages/HomeLogin.js
  food-saviour/src/pages/Login.js
  food-saviour/src/pages/Sharing.js
  food-saviour/src/pages/TestAPI.js
  food-saviour/src/pages/Tracker.js
  food-saviour/src/reportWebVitals.js
Labels: Chore

#87 save tracker data to backend
  food-saviour/src/pages/Tracker.js
Labels: Task

#91 Route protection added for all pages
  food-saviour/src/App.js
  food-saviour/src/pages/Home.js
  food-saviour/src/pages/Login.js
  food-saviour/src/util/authProtected.js
Labels: Chore

#95 Remove social login links
  food-saviour/src/pages/Login.js
Labels: Chore

#104 Store user id on login
  food-saviour/src/components/Logout.js
  food-saviour/src/pages/Login.js
Labels: Chore

#103 added validation and entered amount for tracker
  food-saviour/src/css/tracker.css
  food-saviour/src/pages/Tracker.js
Labels: Task

#106 add validation to login
  food-saviour/src/pages/Login.js
Labels: Chore

#107 Add org
  food-saviour/package.json
  food-saviour/src/components/OrgDropdown.js
  food-saviour/src/components/Sidebar.js
  food-saviour/src/pages/Login.js
  food-saviour/src/pages/Tracker.js
Labels: Chore, Task

#109 fix
  food-saviour/src/pages/Sharing.js
Labels: Chore

#110 Active Waste Type fetch from backend
  food-saviour/src/App.js
  food-saviour/src/pages/Tracker.js
  food-saviour/src/util/TrackerLoading.js
Labels: Chore

#117 New sharing page
  food-saviour/src/pages/Sharing.js
Labels: bug, Chore, Task

#118 Change sharing page over to MDB library
  food-saviour/src/pages/Sharing.js
Labels: Chore

#123 Sharing page update and roles
  food-saviour/src/components/OrgDropdown.js
  food-saviour/src/components/RoleDropdown.js
  food-saviour/src/pages/Login.js
  food-saviour/src/pages/Sharing.js
  food-saviour/src/util/Generate.js
  food-saviour/src/util/SharingLoading.js
Labels: Chore, Task

#120 Landing page styling and documentation
  food-saviour/package-lock.json
  food-saviour/package.json
  food-saviour/public/documentation.pdf
  food-saviour/public/images/foodsaviour_logo.svg
  food-saviour/public/images/foodsaviour_logo_bg.svg
  food-saviour/src/components/Documentation.js
  food-saviour/src/components/Navbar.js
  food-saviour/src/css/App.css
  food-saviour/src/css/index.css
  food-saviour/src/pages/Home.js
  food-saviour/src/pages/HomeLogin.js
  food-saviour/src/pages/Login.js
  food-saviour/src/pages/Tracker.js
Labels: Task

#126 added tracker form validation
  food-saviour/src/pages/Tracker.js
Labels: Task
