Repository COSC-499-Group-C/FoodSaviour-frontend, pull requests merged in 2023-01, with the labels that each got.

#5 Added first 6 templates
  Old/DjangoProject/Project/templates/base.html
  Old/DjangoProject/Project/templates/fullwidth.html
  Old/DjangoProject/Project/templates/home.html
  Old/DjangoProject/Project/templates/home_loggedin.html
  Old/DjangoProject/Project/templates/login.html
  Old/DjangoProject/Project/templates/metrics.html
Labels: enhancement

#3 Added everything EXCEPT template files
  Old/DjangoProject/Project/Forms/MetricForms.py
  Old/DjangoProject/Project/Forms/__pycache__/MetricForms.cpython-38.pyc
  Old/DjangoProject/Project/Forms/__pycache__/newUser.cpython-38.pyc
  Old/DjangoProject/Project/Forms/newUser.py
  Old/DjangoProject/Project/__init__.py
  Old/DjangoProject/Project/__pycache__/__init__.cpython-38.pyc
  Old/DjangoProject/Project/__pycache__/admin.cpython-38.pyc
  Old/DjangoProject/Project/__pycache__/decorators.cpython-38.pyc
  Old/DjangoProject/Project/__pycache__/models.cpython-38.pyc
  Old/DjangoProject/Project/__pycache__/settings.cpython-38.pyc
  Old/DjangoProject/Project/__pycache__/urls.cpython-38.pyc
  Old/DjangoProject/Project/__pycache__/views.cpython-38.pyc
  Old/DjangoProject/Project/__pycache__/wsgi.cpython-38.pyc
  Old/DjangoProject/Project/additionaltags/__init__.py
  Old/DjangoProject/Project/additionaltags/__pycache__/__init__.cpython-38.pyc
  Old/DjangoProject/Project/additionaltags/__pycache__/auth_tag.cpython-38.pyc
  Old/DjangoProject/Project/additionaltags/auth_tag.py
  Old/DjangoProject/Project/admin.py
  Old/DjangoProject/Project/asgi.py
  Old/DjangoProject/Project/decorators.py
  Old/DjangoProject/Project/migrations/0001_initial.py
  Old/DjangoProject/Project/migrations/0002_auto_20221108_1531.py
  Old/DjangoProject/Project/migrations/0003_auto_20221110_0754.py
  Old/DjangoProject/Project/migrations/0004_metricdata_wastetype.py
  Old/DjangoProject/Project/migrations/0005_auto_20221207_1030.py
  Old/DjangoProject/Project/migrations/__init__.py
  Old/DjangoProject/Project/migrations/__pycache__/0001_initial.cpython-38(1).pyc
  Old/DjangoProject/Project/migrations/__pycache__/0002_auto_20221108_1531.cpython-38(1).pyc
  Old/DjangoProject/Project/migrations/__pycache__/0003_auto_20221110_0754.cpython-38(1).pyc
  Old/DjangoProject/Project/migrations/__pycache__/0004_metricdata_wastetype.cpython-38.pyc
  Old/DjangoProject/Project/migrations/__pycache__/0005_auto_20221207_1030.cpython-38.pyc
  Old/DjangoProject/Project/migrations/__pycache__/__init__.cpython-38.pyc
  Old/DjangoProject/Project/models(1).py
  Old/DjangoProject/Project/settings.py
  Old/DjangoProject/Project/static/Project/foodsaviour.png
  Old/DjangoProject/Project/static/Project/home.css
  Old/DjangoProject/Project/static/Project/metrics.css
  Old/DjangoProject/Project/static/Project/metrics.js
  Old/DjangoProject/Project/static/Project/metrics_icon.png
  Old/DjangoProject/Project/static/Project/orgs_icon.png
  Old/DjangoProject/Project/static/Project/register.css
  Old/DjangoProject/Project/static/Project/styles.css
  Old/DjangoProject/Project/urls.py
  Old/DjangoProject/Project/views.py
  Old/DjangoProject/Project/wsgi.py
  Old/DjangoProject/manage.py
  Old/DjangoProject/project.db
  Old/DjangoProject/requirements.txt
  Old/Old.md
Labels: Chore

#10 spacing in css
  Old/DjangoProject/Project/static/Project/metrics.css
  Old/DjangoProject/Project/static/Project/register.css
Labels: Chore

#19 Meeting minutes 01-11 and 01-18
  .gitignore
  Old/DjangoProject/Project/models.py
  documents/client/meeting-minutes/2023-01-11.md
  documents/client/meeting-minutes/2023-01-18.md
Labels: documentation

#20 Delete files in wrong directory
  Old/AboutUs.md
  Old/README.md
  Old/__init__.py
  Old/admin.py
  Old/asgi.py
  Old/base.html
  Old/cubic.py
  Old/decorators.py
  Old/definitions.md
  Old/division.py
  Old/foodsaviour.png
  Old/fullwidth.html
  Old/home.html
  Old/home_loggedin.html
  Old/login.html
  Old/metrics.css
  Old/metrics.html
  Old/metrics.js
  Old/metrics_icon.png
  Old/models.py
  Old/org_page.html
  Old/orgs_icon.png
  Old/power.py
  Old/register.css
  Old/register.html
  Old/remainder.py
  Old/remainderTest.py
  Old/settings.py
  Old/sidebar_left.html
  Old/sidebar_right.html
  Old/styles.css
  Old/sumproduct.py
  Old/test_cube.py
  Old/test_division.py
  Old/test_power.py
  Old/test_sumproduct.py
  Old/tracker.html
  Old/urls.py
  Old/views.py
  Old/wsgi.py
Labels: Chore

#25 Update .gitignore
  .gitignore
Labels: Chore

#34 change
  Old/random/home_loggedin.html
  Old/random/metrics.js
Labels: documentation, Chore, Exploration, Task

#39 Client Meeting Minutes 2023-01-25
  documents/client/meeting-minutes/2023-01-25.md
Labels: Task

#43 Add Login.js and fix a few small things
  food-saviour/public/images/logo.png
  food-saviour/src/App.js
  food-saviour/src/Login.js
  food-saviour/src/index.js
Labels: Chore

#48 Extra pr
  food-saviour/public/favicon.ico
  food-saviour/public/index.html
  food-saviour/public/logo192.png
  food-saviour/public/logo512.png
  food-saviour/public/robots.txt
Labels: Chore

#47 Remove unnecessary files in public/
  food-saviour/public/favicon.ico
  food-saviour/public/logo192.png
  food-saviour/public/logo512.png
  food-saviour/public/robots.txt
Labels: Chore
