Repository COSC-499-Group-C/FoodSaviour-frontend, pull requests merged in 2023-02, with the labels that each got.

#50 Basic router functionality implemented
  .gitignore
  food-saviour/package-lock.json
  food-saviour/package.json
  food-saviour/src/App.js
  food-saviour/src/pages/Home.js
  food-saviour/src/pages/Login.js
Labels: Chore

#54 Small change to the button to be "Login or Register"
  food-saviour/src/pages/Home.js
Labels: Chore

#57 Added routing address for sharing page
  food-saviour/src/App.js
  food-saviour/src/css/sharing.css
  food-saviour/src/pages/Sharing.js
Labels: Task

#58 update index.html
  food-saviour/public/index.html
Labels: Chore

#62 Basic axios installation, no functionality yet
  food-saviour/package-lock.json
  food-saviour/package.json
  food-saviour/src/App.js
  food-saviour/src/pages/Login.js
  food-saviour/src/pages/TestAPI.js
Labels: Chore, Task

#60 Tracker Page
  food-saviour/package-lock.json
  food-saviour/package.json
  food-saviour/src/App.js
  food-saviour/src/pages/Login.js
  food-saviour/src/pages/PieChart.js
  food-saviour/src/pages/Tracker.js
Labels: Task

#69 Navbar and Home logged-in
  food-saviour/public/images/sharing.png
  food-saviour/public/images/tracker.png
  food-saviour/src/App.js
  food-saviour/src/addons/Navbar.js
  food-saviour/src/pages/HomeLogin.js
  food-saviour/src/pages/Login.js
Labels: Task

#66 Tracker Page
  food-saviour/src/css/tracker.css
  food-saviour/src/pages/PieChart.js
  food-saviour/src/pages/Tracker.js
Labels: Task

#65 Changes added to frontend
  food-saviour/.env
  food-saviour/src/actions/auth.js
  food-saviour/src/components/CSRFToken.js
  food-saviour/src/index.js
  food-saviour/src/pages/Login.js
Labels: Chore
